[package]
name = "justdeploy"
version = "0.1.0"
description = "A rust based deployment control panel"
authors = ["Soham Ghugare <soham.ghugare@gmail.com>"]
license = "MIT"
categories = ["development-tools"]
repository = "https://github.com/quriousprof/justdeploy"
edition = "2024"
readme = "../README.md"

[dependencies]
crossterm = "0.29.0"
ratatui = "0.30.2"
